# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e704f3c1a092a2f654aad51804fb1b6388c3d5245d13d21ee44ba204e380a7d62757a27356c68799438133bb79892e7eebbc772cfd060a270384f135a4e64c9c

test:
  secret_key_base: 348bd5186981ef6b10f4f937718c8e41e1817dc63181622cc518730974e6963f1b065ea8d03b988040e54df1e251af36c65ced3414453d35414d801bc526a7db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
